/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ComponentInpoutEdit: typeof import('./../src/renderer/src/components/componentInpoutEdit.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTree: typeof import('element-plus/es')['ElTree']
    IconElOkCircle: typeof import('~icons/el/ok-circle')['default']
    IconMaterialSymbolsCloseRounded: typeof import('~icons/material-symbols/close-rounded')['default']
    IconMaterialSymbolsMinimize: typeof import('~icons/material-symbols/minimize')['default']
    IconMaterialSymbolsSelectWindow: typeof import('~icons/material-symbols/select-window')['default']
    IconMaterialSymbolsSquareOutlineRounded: typeof import('~icons/material-symbols/square-outline-rounded')['default']
    ParameterConfig: typeof import('./../src/renderer/src/components/ParameterConfig.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepBar: typeof import('./../src/renderer/src/components/stepBar.vue')['default']
    TitleBar: typeof import('./../src/renderer/src/components/titleBar.vue')['default']
  }
}
